const translations = {
    id: {
        "kembali_berita": "Kembali ke Daftar Berita",
        // Navbar
        "nav.about": "Tentang Kami",
        "nav.business": "Bisnis",
        "nav.investor": "Hubungan Investor",
        "nav.sustainability": "Sustainability",
        "nav.news": "Berita & Media",
        "nav.career": "Karir",
        "nav.contact": "HUBUNGI KAMI",
        "nav.about.profile": "Profil Perusahaan",
        "nav.about.vision": "Visi Misi",
        "nav.about.values": "Tata Nilai",
        "nav.about.history": "Sejarah",
        "nav.about.board": "Dewan Komisaris",
        "nav.about.directors": "Direksi",
        "nav.about.structure": "Struktur Organisasi",
        "nav.about.certification": "Sertifikasi",
        "nav.about.awards": "Penghargaan",
        "nav.biz.transport": "Transportasi",
        "nav.biz.inventory": "Inventory Management",
        "nav.biz.other": "Lainnya",
        "nav.biz.fleet": "Fleet Management",

        // Hero
        "hero.tag": "Penyaluran dan Transportasi",
        "hero.title": "Logistik Energi, Andal, <br>Aman, Terintegrasi",
        "hero.desc": "Memastikan pasokan energi nasional — aman, tepat waktu, tepat jumlah — dari Aceh hingga Papua.",
        "hero.btn.route": "Lihat Rute Penyaluran",
        "hero.btn.contact": "Hubungi Kami",
        "hero.track.subtitle": "REAL-TIME MONITORING",
        "hero.track.title": "Lacak Pengiriman",
        "hero.track.desc": "Masukkan nomor Delivery Order (DO) untuk memantau status pengiriman BBM & LPG Anda secara langsung.",
        "hero.track.placeholder": "Masukkan No. DO (Contoh: DO-PATRA-001)",
        "hero.track.btn": "LACAK SEKARANG",

        // Ticker
        "ticker.quality": "Tepat Mutu",
        "ticker.time": "Tepat Waktu",
        "ticker.quantity": "Tepat Jumlah",
        "ticker.place": "Tepat Tempat",
        "ticker.hsse": "HSSE Terintegrasi",
        "ticker.tracking": "Real-Time Tracking",
        "ticker.national": "Distribusi Nasional",
        "ticker.modern": "Armada Modern",

        // About Section
        "about.tag": "EST. SEJAK 1997",
        "about.title": "Tentang<br>Patra Logistik",
        "about.desc": "Temukan bagaimana kami menghadirkan efisiensi operasional yang tak tertandingi dalam distribusi energi. Dengan jaringan yang luas dan teknologi terkini, kami memastikan setiap pengiriman energi sampai tepat sasaran.",
        "about.stat.city": "Kota Operasi",
        "about.stat.accuracy": "Tracking Accuracy",
        "about.stat.ontime": "On-Time Delivery",
        "about.btn": "PELAJARI LEBIH LANJUT",

        // Services
        "services.tag": "Layanan Kami",
        "services.title": "Layanan & Solusi Logistik",
        "services.desc": "Kami hadir dengan layanan terintegrasi untuk memastikan setiap tetes energi sampai ke tujuan dengan aman dan tepat.",
        "services.tab.transport": "Transportasi",
        "services.tab.inventory": "Inventory Management",
        "services.tab.other": "Other Business",
        "services.card.more": "Selengkapnya",

        // Services Transport
        "srv.trans.1.title": "Pengangkutan BBM",
        "srv.trans.1.desc": "Pengiriman pelumas industri & otomotif Pertamina secara aman dengan jaminan keaslian dan anti-kontaminasi.",
        "srv.trans.2.title": "Pengangkutan Gas",
        "srv.trans.2.desc": "Pengiriman pelumas industri & otomotif Pertamina secara aman dengan jaminan keaslian dan anti-kontaminasi.",
        "srv.trans.3.title": "Pengangkutan Pelumas",
        "srv.trans.3.desc": "Pengiriman pelumas industri & otomotif Pertamina secara aman dengan jaminan keaslian dan anti-kontaminasi.",
        "srv.trans.4.title": "Transportasi Multimoda",
        "srv.trans.4.desc": "Solusi pengiriman terintegrasi antar moda darat, laut, dan udara secara efisien.",
        "srv.trans.5.title": "Pengangkutan Limbah B3",
        "srv.trans.5.desc": "Layanan pengelolaan dan pengangkutan limbah berbahaya tersertifikasi dan aman.",

        // Map Section
        "map.tag": "LAYANAN KAMI",
        "map.title": "Wilayah Operasi",
        "map.desc": "Menghubungkan rantai pasok energi Indonesia dari Sabang sampai Merauke secara presisi dan berkesinambungan melalui unit region strategis.",
        "map.instruction": "INTERAKTIF: KLIK WILAYAH REGION UNTUK DETAIL JANGKAUAN",
        "map.stat.1": "Retail Fuel Transport",
        "map.stat.2": "Industrial Fuel Transport",
        "map.stat.3": "Vendor Managed Inventory",
        "map.stat.4": "Total Project & Layanan",
        "map.stat.unit.project": "PROJECT",
        "map.stat.unit.location": "LOKASI",
        "map.stat.unit.total": "TOTAL",
        "map.panel.btn": "Informasi Project & Layanan",

        // RTC Section
        "rtc.pill": "PUSAT KENDALI OPERASI DIGITAL",
        "rtc.title": "Digital Logistic <span class='text-light-blue'>Solution</span>",
        "rtc.desc": "Sistem pengawasan digital terpadu yang memantau pergerakan armada, kondisi pengemudi, serta keselamatan muatan energi secara real-time demi mewujudkan <span class='text-bold-blue'>Zero Accident & High Reliability</span>.",
        "rtc.card.more": "SELENGKAPNYA",
        "rtc.card1.pill": "IOT TRACKER",
        "rtc.card1.title": "Fleet Management<br>System",
        "rtc.card1.desc": "Solusi GPS Tracker untuk Keamanan Armada Secara Real-Time",
        "rtc.card2.pill": "AI CAMERA",
        "rtc.card2.title": "Fatigue<br>Sensor",
        "rtc.card2.desc": "Mendeteksi kelelahan pengemudi dengan AI",
        "rtc.card3.pill": "SAFETY",
        "rtc.card3.title": "Over-Speed<br>Buzzer",
        "rtc.card3.desc": "Peringatan otomatis saat melebihi batas kecepatan",
        "rtc.card4.pill": "DASHCAM",
        "rtc.card4.title": "In-Cabin<br>Camera",
        "rtc.card4.desc": "Pemantauan visual kabin armada 24/7",

        // Footer
        "footer.desc": "Berkomitmen pada distribusi energi yang aman, andal, dan terintegrasi ke seluruh pelosok negeri.",
        "footer.col1": "PERUSAHAAN",
        "footer.col2": "INFORMASI PUBLIK",
        "footer.col3": "KANTOR PUSAT",
        "footer.copyright": "© 2026 PT Pertamina Patra Logistik. Hak Cipta Dilindungi Undang-Undang."
    },
    en: {
        "kembali_berita": "Back to News List",
        // Navbar
        "nav.about": "About Us",
        "nav.business": "Business",
        "nav.investor": "Investor Relations",
        "nav.sustainability": "Sustainability",
        "nav.news": "News & Media",
        "nav.career": "Careers",
        "nav.contact": "CONTACT US",
        "nav.about.profile": "Company Profile",
        "nav.about.vision": "Vision & Mission",
        "nav.about.values": "Core Values",
        "nav.about.history": "History",
        "nav.about.board": "Board of Commissioners",
        "nav.about.directors": "Board of Directors",
        "nav.about.structure": "Organizational Structure",
        "nav.about.certification": "Certifications",
        "nav.about.awards": "Awards",
        "nav.biz.transport": "Transportation",
        "nav.biz.inventory": "Inventory Management",
        "nav.biz.other": "Other Services",
        "nav.biz.fleet": "Fleet Management",

        // Hero
        "hero.tag": "Distribution and Transportation",
        "hero.title": "Energy Logistics, Reliable, <br>Safe, Integrated",
        "hero.desc": "Ensuring the national energy supply — safely, on time, in the right quantity — from Aceh to Papua.",
        "hero.btn.route": "View Distribution Routes",
        "hero.btn.contact": "Contact Us",
        "hero.track.subtitle": "REAL-TIME MONITORING",
        "hero.track.title": "Track Shipment",
        "hero.track.desc": "Enter your Delivery Order (DO) number to monitor the delivery status of your Fuel & LPG directly.",
        "hero.track.placeholder": "Enter DO Number (e.g., DO-PATRA-001)",
        "hero.track.btn": "TRACK NOW",

        // Ticker
        "ticker.quality": "Right Quality",
        "ticker.time": "On Time",
        "ticker.quantity": "Right Quantity",
        "ticker.place": "Right Place",
        "ticker.hsse": "Integrated HSSE",
        "ticker.tracking": "Real-Time Tracking",
        "ticker.national": "National Distribution",
        "ticker.modern": "Modern Fleet",

        // About Section
        "about.tag": "EST. SINCE 1997",
        "about.title": "About<br>Patra Logistik",
        "about.desc": "Discover how we deliver unparalleled operational efficiency in energy distribution. With a vast network and latest technology, we ensure every energy shipment arrives perfectly on target.",
        "about.stat.city": "Operating Cities",
        "about.stat.accuracy": "Tracking Accuracy",
        "about.stat.ontime": "On-Time Delivery",
        "about.btn": "LEARN MORE",

        // Services
        "services.tag": "Our Services",
        "services.title": "Logistics Solutions & Services",
        "services.desc": "We provide integrated services to ensure every drop of energy reaches its destination safely and accurately.",
        "services.tab.transport": "Transportation",
        "services.tab.inventory": "Inventory Management",
        "services.tab.other": "Other Business",
        "services.card.more": "Read More",

        // Services Transport
        "srv.trans.1.title": "Fuel Transport",
        "srv.trans.1.desc": "Safe delivery of Pertamina industrial & automotive fuels with guaranteed authenticity and zero contamination.",
        "srv.trans.2.title": "Gas Transport",
        "srv.trans.2.desc": "Safe delivery of Pertamina industrial & automotive gas with guaranteed authenticity and zero contamination.",
        "srv.trans.3.title": "Lubricants Transport",
        "srv.trans.3.desc": "Safe delivery of Pertamina industrial & automotive lubricants with guaranteed authenticity and zero contamination.",
        "srv.trans.4.title": "Multimodal Transport",
        "srv.trans.4.desc": "Integrated shipping solutions across land, sea, and air efficiently.",
        "srv.trans.5.title": "B3 Waste Transport",
        "srv.trans.5.desc": "Certified and safe hazardous waste management and transportation services.",

        // Map Section
        "map.tag": "OUR COVERAGE",
        "map.title": "Operational Areas",
        "map.desc": "Connecting Indonesia's energy supply chain from Sabang to Merauke precisely and sustainably through strategic regional units.",
        "map.instruction": "INTERACTIVE: CLICK REGIONAL AREAS FOR COVERAGE DETAILS",
        "map.stat.1": "Retail Fuel Transport",
        "map.stat.2": "Industrial Fuel Transport",
        "map.stat.3": "Vendor Managed Inventory",
        "map.stat.4": "Total Projects & Services",
        "map.stat.unit.project": "PROJECTS",
        "map.stat.unit.location": "LOCATIONS",
        "map.stat.unit.total": "TOTAL",
        "map.panel.btn": "Project & Service Information",

        // RTC Section
        "rtc.pill": "DIGITAL OPERATIONS CONTROL CENTER",
        "rtc.title": "Digital Logistic <span class='text-light-blue'>Solution</span>",
        "rtc.desc": "Integrated digital surveillance system that monitors fleet movement, driver conditions, and energy cargo safety in real-time to realize <span class='text-bold-blue'>Zero Accident & High Reliability</span>.",
        "rtc.card.more": "READ MORE",
        "rtc.card1.pill": "IOT TRACKER",
        "rtc.card1.title": "Fleet Management<br>System",
        "rtc.card1.desc": "GPS Tracker solution for Real-Time Fleet Security",
        "rtc.card2.pill": "AI CAMERA",
        "rtc.card2.title": "Fatigue<br>Sensor",
        "rtc.card2.desc": "Detects driver fatigue utilizing AI",
        "rtc.card3.pill": "SAFETY",
        "rtc.card3.title": "Over-Speed<br>Buzzer",
        "rtc.card3.desc": "Automatic warning when exceeding speed limits",
        "rtc.card4.pill": "DASHCAM",
        "rtc.card4.title": "In-Cabin<br>Camera",
        "rtc.card4.desc": "24/7 visual monitoring of the fleet cabin",

        // Footer
        "footer.desc": "Committed to safe, reliable, and integrated energy distribution across the nation.",
        "footer.col1": "COMPANY",
        "footer.col2": "PUBLIC INFORMATION",
        "footer.col3": "HEAD OFFICE",
        "footer.copyright": "© 2026 PT Pertamina Patra Logistik. All Rights Reserved."
    }
};
