const translations = {
    id: {
        "biz_0": "Solusi Logistik & Energi",
        "biz_1": "Bisnis Kami",
        "biz_2": "Menyediakan rantai pasokan logistik energi yang terintegrasi, andal, dan berstandar internasional di seluruh Indonesia.",
        "biz_3": "Patra Logistik hadir sebagai mitra transportasi logistik energi yang andal, dengan jaringan layanan yang luas, penerapan aspek keselamatan yang ketat, serta dukungan teknologi untuk memastikan setiap proses distribusi berjalan aman, efisien, dan terpantau secara real-time.",
        "biz_4": "Patra Logistik menyediakan layanan pengangkutan Bahan Bakar Minyak (BBM) melalui pengelolaan Awak Mobil Tangki (AMT) dan Mobil Tangki BBM yang terintegrasi, andal, dan berorientasi pada keselamatan. Layanan ini mendukung penyaluran BBM dari Fuel Terminal menuju SPBU, industri, maupun titik distribusi lainnya.",
        "biz_5": "> Skema Layanan",
        "biz_6": "Depot BBM Pertamina",
        "biz_7": "Armada Supply Patra Logistik",
        "biz_8": "Lokasi Serah Terima",
        "biz_9": "Patra Logistik menyediakan layanan pengangkutan Liquefied Petroleum Gas (LPG) menggunakan armada truk tangki khusus bertekanan yang dirancang untuk menjaga keamanan, kualitas, dan keandalan distribusi gas dalam bentuk cair.",
        "biz_10": "Layanan ini mendukung penyaluran pasokan LPG secara massal dari depot atau terminal utama menuju Stasiun Pengisian Bulk Elpiji (SPBE) maupun titik layanan lainnya.",
        "biz_11": "> Skema Layanan",
        "biz_12": "Skema Distribusi LPG (Mother-Daughter System)",
        "biz_13": "Mother Station",
        "biz_14": "Transport (Skid Tank)",
        "biz_15": "Daughter Station",
        "biz_16": "Skema Distribusi LNG (Virtual Pipeline System)",
        "biz_17": "LNG Plant/LNG Terminal",
        "biz_18": "LNG Filling Station",
        "biz_19": "Trucking + ISO Tank",
        "biz_20": "Regasification Facility",
        "biz_21": "LNG Customer",
        "biz_22": "Mengelola distribusi rantai pasok pelumas secara dua arah, menjangkau area operasional mulai dari Depot Supply Point (DSP) hingga ke distributor di seluruh wilayah Indonesia maupun sebaliknya.",
        "biz_23": "> Skema Layanan",
        "biz_24": "Ujung Berung",
        "biz_25": "DISTRIBUTOR",
        "biz_26": "DISTRIBUTOR",
        "biz_27": "Door to Door",
        "biz_28": "Layanan distribusi bahan bakar aviasi (Avtur) secara andal dan berstandar internasional dari Terminal Bahan Bakar Minyak (TBBM) menuju Depot Pengisian Pesawat Udara (DPPU) hingga pengisian langsung ke maskapai penerbangan.",
        "biz_29": "Penyaluran Avtur volume besar menggunakan truk tangki (bridger avtur) dari TBBM utama/Kilang menuju tangki penyimpanan DPPU bandara.",
        "biz_30": "Layanan pengisian bahan bakar langsung ke tangki pesawat udara menggunakan refueller truck maupun dispenser sistem hydrant bandara.",
        "biz_31": "> Skema Layanan",
        "biz_32": "Pengangkutan limbah B3 (Bahan Berbahaya dan Beracun) sisa operasional logistik energi dengan izin resmi dan prosedur keselamatan yang sangat ketat untuk memastikan perlindungan lingkungan yang komprehensif.",
        "biz_33": "> Skema Layanan",
        "biz_34": "Penghasil Limbah B3",
        "biz_35": "Fleet B3 Berlisensi",
        "biz_36": "Fasilitas Pengolah B3",
        "biz_37": "Kenapa Perusahaan Mempercayakan Transportasi kepada Patra Logistik?",
        "biz_38": "Nationwide Network",
        "biz_39": "Jaringan operasional yang tersebar di berbagai wilayah Indonesia, mendukung kebutuhan distribusi energi secara luas dan berkelanjutan.",
        "biz_40": "HSSE Principle",
        "biz_41": "Mengedepankan prinsip Health, Safety, Security, and Environment dalam setiap aktivitas operasional untuk memastikan layanan berjalan aman dan sesuai standar.",
        "biz_42": "Cost Effectiveness",
        "biz_43": "Optimalisasi operasional untuk mendukung efisiensi biaya tanpa mengurangi kualitas, keselamatan, dan keandalan layanan.",
        "biz_44": "Real Time Monitoring",
        "biz_45": "Pemantauan armada secara real-time untuk memastikan pergerakan kendaraan, rute, dan aktivitas distribusi dapat terpantau dengan akurat.",
        "biz_46": "Multi-Moda Integration",
        "biz_47": "Mendukung integrasi berbagai moda transportasi untuk menciptakan solusi logistik yang lebih fleksibel, efisien, dan terhubung.",
        "biz_48": "Inventory Management",
        "biz_49": "Kami bertekad untuk memberikan pelayanan terbaik kepada Anda. Dengan beragam armada yang dikelola oleh tim yang memiliki dedikasi dan keahlian, kami berharap dapat menyampaikan keunggulan kepada Anda.",
        "biz_50": "Fuel Terminal Ketapang, berdiri pada tahun 2006, adalah pusat penyimpanan dan distribusi energi strategis di Kalimantan Barat. Terletak di alur Sungai Pawan, terminal ini vital menyuplai BBM (Biosolar, Pertalite, Pertamax) ke wilayah Ketapang dan Kayong Utara dengan kapasitas tangki timbun mencapai 7.200 kiloliter.",
        "biz_51": "FT Ketapang dilengkapi dengan dermaga untuk muat dan bongkar, serta pengisian bahan bakar dengan kapasitas 3.000 DWT.",
        "biz_52": "Kapasitas DWT",
        "biz_53": "Total Kapasitas",
        "biz_54": "Patra Logistik berperan strategis dalam pengelolaan gudang dan distribusi pelumas PT Pertamina Lubricants (PTPL). Sinergi ini difokuskan pada penguatan rantai pasok (supply chain), optimalisasi infrastruktur warehouse, dan peningkatan layanan distribusi.",
        "biz_55": "Pengelolaan dan pendistribusian Depot Supply Point PT Pertamina Lubricants ini meliputi pengelolaan Gudang seperti Receiving, Storaging, Picking, serta menyediakan SDM guna untuk operasional Warehousing.",
        "biz_56": "DPPU (Depot Pengisian Pesawat Udara) adalah bentuk kolaborasi antara Pertamina Patra Niaga dengan PT Patra Logistik untuk mengelola operasional pengisian bahan bakar pesawat di berbagai bandara di Indonesia. Skema ini bertujuan memastikan keandalan stok avtur dan efisiensi pelayanan pengisian pesawat.",
        "biz_57": "Manajemen pengelolaan bahan bakar yang meliputi pengiriman bahan bakar, penyimpanan bahan bakar, hingga penyaluran bahan bakar serta pemeliharaan sarana penyimpanan bahan bakar yang tersedia di lokasi konsumen (Vendor Held Stocks).",
        "biz_58": "> Skema Alur Operasi VHS",
        "biz_59": "Sumber Pasokan",
        "biz_60": "Depot BBM Patra Niaga",
        "biz_61": "🚢 Kapal (Laut)",
        "biz_62": "🚚 Armada (Darat)",
        "biz_63": "Lokasi Konsumen",
        "biz_64": "Storage VHS",
        "biz_65": "Fasilitas Storage",
        "biz_66": "Storage VHS",
        "biz_67": "🚢 Kapal Supply",
        "biz_68": "⚙️ Flowmeter",
        "biz_69": "🚛 Service Tank Truck",
        "biz_70": "Destinasi Akhir",
        "biz_71": "Equipment Customer",
        "biz_72": "(Kapal, genset, alat berat, dll.)",
        "biz_73": "Layanan pengelolaan gudang material proyek, suku cadang, dan peralatan pendukung untuk industri energi secara profesional. Kami menerapkan WMS (Warehouse Management System) modern untuk memastikan pencatatan inventori yang akurat, pelacakan real-time, dan tata letak penyimpanan yang optimal.",
        "biz_74": "Material Storage",
        "biz_75": "Penyimpanan material proyek dan peralatan industri dengan tata ruang aman dan higienis.",
        "biz_76": "Sparepart Management",
        "biz_77": "Pencatatan stock level suku cadang vital secara berkala untuk meminimalkan waktu henti (downtime) operasional.",
        "biz_78": "Other Business",
        "biz_79": "Kami bertekad untuk memberikan pelayanan terbaik kepada Anda. Dengan beragam armada yang dikelola oleh tim yang memiliki dedikasi dan keahlian, kami berharap dapat menyampaikan keunggulan kepada Anda.",
        "biz_80": "Layanan penyewaan kendaraan ringan penumpang (Light Passenger Vehicle) untuk mendukung kegiatan operasional perkantoran dan lapangan mitra kerja di berbagai daerah operasional seluruh Indonesia. Armada kami terawat secara berkala dan didukung oleh sistem pemantauan berkendara yang aman.",
        "biz_81": "Layanan pengurusan administrasi kepabeanan, ekspor-impor, serta perizinan kepelabuhanan (Customs Clearance) secara cepat, tepat, dan patuh terhadap regulasi hukum yang berlaku. Kami mempermudah proses kepabeanan komoditas energi Anda agar alur distribusi berjalan lancar.",
        "biz_82": "Solusi teknologi informasi yang terintegrasi untuk mendukung operasional logistik, termasuk sistem manajemen transportasi (TMS), pelacakan real-time, integrasi data supply chain, dan pemeliharaan infrastruktur TI di wilayah operasi terpencil.",
        "biz_83": "Penyediaan tenaga kerja profesional dan bersertifikat (seperti pengemudi mobil tangki/AMT, staf logistik, operasional lapangan) untuk menjamin standar keselamatan (HSSE) yang ketat dan efisiensi kerja tinggi pada ekosistem distribusi energi Anda.",
        "biz_84": "Layanan pengangkutan produk energi non-BBM, seperti Fatty Acid Methyl Ester (FAME) dan refrigeran ramah lingkungan Breezon MC (refrigeran hidrokarbon dari Pertamina) untuk kebutuhan industri, otomotif, dan pendingin ruangan ramah lingkungan.",
        "biz_85": "Pengangkutan FAME",
        "biz_86": "Pengangkutan FAME (Fatty Acid Methyl Ester) sebagai bahan campuran utama biodiesel guna mendukung bauran energi terbarukan nasional serta program ramah lingkungan pemerintah.",
        "biz_87": "Bioenergy Distribution",
        "biz_88": "Pengangkutan BreezonMC",
        "biz_89": "Distribusi dan pengangkutan refrigeran hidrokarbon Breezon MC produksi Pertamina sebagai solusi media pendingin udara ramah lingkungan yang aman dan berefisiensi energi tinggi.",
        "biz_90": "Green Refrigerant Transport",
        "biz_91": "Fleet Management",
        "biz_92": "Melalui layanan",
        "biz_93": "Fleet Management",
        "biz_94": "yang terintegrasi, Patra Logistik menghadirkan solusi menyeluruh untuk memastikan setiap armada beroperasi dalam performa terbaik, mulai dari pengelolaan operasional harian, pemantauan performa kendaraan, perawatan dan pemeliharaan berkala, hingga optimalisasi utilisasi armada.",
        "biz_95": "Servis dan solusi yang kami kelola",
        "biz_96": "Fleet Operations",
        "biz_97": "Lacak seluruh transaksi operasional kendaraan, pantau penggunaan bensin, hingga pencatatan riwayat perjalanan secara akurat untuk maksimalkan penggunaan masing-masing kendaraan.",
        "biz_98": "Route Optimization",
        "biz_99": "Ketahui rute terpendek dan tercepat untuk sampai tujuan dengan mempertimbangkan faktor-faktor seperti kondisi lalu lintas, jarak, perkiraan cuaca hingga waktu tempuh. Meningkatkan efisiensi waktu perjalanan.",
        "biz_100": "Maintenance Management",
        "biz_101": "Notifikasi real-time ketika armada Anda membutuhkan perbaikan. Menetapkan jadwal pemeliharaan berdasarkan interval waktu secara otomatis. Minimalisir downtime kendaraan Anda.",
        "biz_102": "Driver Management",
        "biz_103": "Kelola seluruh data pengemudi dalam driver management system yang terpusat. Pantau lokasi, jam kerja, dan aktivitas driver secara real-time.",
        "biz_104": "Seamless Integration IoT",
        "biz_105": "Kemudahan integrasi geofencing, GPS, odometer, sensor, dan masih banyak lagi untuk memantau lokasi, kecepatan, dan kondisi operasional kendaraan secara real-time.",
        "biz_106": "Report Performance",
        "biz_107": "Menyediakan data terperinci mengenai penggunaan kendaraan, termasuk konsumsi bahan bakar hingga kecepatan, yang dapat digunakan untuk membuat keputusan bisnis yang lebih baik.",
        "biz_108": "Sistem Operasional & Jangkauan Depot",
        "biz_109": "Maintenance Management System (MMS)",
        "biz_110": "Security & Surveillance",
        "biz_111": "GPS TRACK MT & DASHCAM",
        "biz_112": "Operation & Maintenance",
        "biz_113": "Tyre Management System (TMS)",
        "biz_114": "Traffic Road Control (TRC)",
        "biz_115": "Human Resource (Own Use)",
        "biz_116": "Fleet Project",
        "biz_117": "Kantor Pusat",
        "biz_118": "Garden Avenue Rasuna Lantai 1-3, Jalan Epicentrum Tengah No. 3, RT.2/RW.5, Karet Kuningan, Kecamatan Setiabudi, Jakarta Selatan.",
        "biz_119": "(021)-25196699",
        "biz_120": "info.patralogistik@pertamina.com",
        "biz_121": "Whistle Blowing System",
        "biz_122": "https://pertaminaclean.tipoffs.info/",
        "biz_123": "AFFILIATE OF:",
        "biz_124": "PERTAMINA PATRA NIAGA",
        "biz_125": "Semua konten, logo, dan hak cipta dilindungi oleh PT Patra Logistik dan                         PT Pertamina (Persero).",

        "about_0": "Profil Korporasi",
        "about_1": "Mengenal Patra Logistik",
        "about_2": "Solusi logistik energi terintegrasi dengan standar keselamatan dan kepatuhan tinggi untuk negeri.",
        "about_3": "Visi & Misi",
        "about_4": "\"Menjadi Perusahaan Penyedia Jasa Logistik Energi Terintegrasi yang Terkemuka, Handal, dan Berstandar Kelas Dunia di Indonesia.\"",
        "about_5": "Menyelenggarakan jasa logistik energi terintegrasi yang efisien, aman, dan tepat waktu untuk menjamin pasokan energi nasional.",
        "about_6": "Menerapkan praktik HSSE (Health, Safety, Security & Environment) di tingkat tertinggi pada seluruh rantai operasional.",
        "about_7": "Membangun sinergi bisnis yang saling menguntungkan dengan mitra strategis serta memberikan nilai tambah optimal kepada pemangku kepentingan.",
        "about_8": "Nilai Perusahaan (AKHLAK)",
        "about_9": "Sebagai anak perusahaan dari grup BUMN Pertamina, kami memegang teguh nilai inti AKHLAK dalam menjalankan fungsi operasional sehari-hari:",
        "about_10": "Memegang teguh kepercayaan yang diberikan dengan integritas tinggi dan bertanggung jawab penuh.",
        "about_11": "Terus belajar, berinovasi, dan meningkatkan kapabilitas untuk memberikan hasil kerja terbaik.",
        "about_12": "Saling peduli, berempati, dan menghargai keberagaman serta kontribusi setiap individu.",
        "about_13": "Berdedikasi tinggi dan mengutamakan kepentingan bangsa serta kemajuan perusahaan.",
        "about_14": "Cepat menyesuaikan diri, lincah menghadapi tantangan bisnis, dan terus melakukan perbaikan.",
        "about_15": "KOLABORATIF",
        "about_16": "Membangun kerja sama sinergis demi tujuan bersama dan pemenuhan energi nasional.",
        "about_17": "SEJARAH PERUSAHAAN",
        "about_18": "PT Patra Logistik berawal dari PT. Elnusa Kawasan Komersial yang didirikan pada tanggal 30 Agustus 1996 untuk mengelola Kawasan Komersil di Graha Elnusa TB Simatupang Kav 1-B, Jakarta Selatan. Tanggal 16 Agustus 2005 PT. Elnusa Kawasan Komersial berubah nama menjadi PT. Patra Logistik dan menjadi subsidiary dari PT. Pertamina Patra Niaga. PT Patra Logistik sekarang beralamatkan di Garden Avenue Rasuna lantai (1-3) Jl. Epicentrum Tengah No. 3 Kel. Setiabudi Jakarta Selatan.",
        "about_19": "PT Patra Logistik bergerak dibidang usaha hilir migas yang fokus pada kegiatan penyedia jasa logistik dan support jasa logistik lainnya. Berkomitmen dan berusaha penuh dengan sumber daya yang kami miliki untuk mengokohkan kompetensinya sebagai Perusahaan Logistik dengan memberikan layanan yang prima, PT Patra Logistik mengedepankan etos kerja yang profesional, transparan, dengan integritas yang tinggi yang berorientasi pada kepuasan pelanggan, stakeholder dan kesejahteraan serta tanggap dalam menghadapi dinamika",
        "about_20": "The Journey 2012–2013",
        "about_21": "VHS BBM Timah, Pembangunan dan Pengoperasian DPPU Labuan Bajo",
        "about_22": "The Journey 2016–2017",
        "about_23": "Franco BBM TNI, Pengelolaan KSO DPPU H.A.S. Hanandjoeddin",
        "about_24": "The Journey 2018–2019",
        "about_25": "Transportasi:",
        "about_26": "Transportasi Pelumas dari DSP Plumpang ke seluruh wilayah Indonesia Bagian Barat",
        "about_27": "Transportasi CNG",
        "about_28": "Warehouse Management System",
        "about_29": "Customs Clearance",
        "about_30": "The Journey 2019–2020",
        "about_31": "The Journey 2020–2021",
        "about_32": "Ekspansi pasar ke BUMN Non Pertamina Group dan Ekspansi bisnis special haulage heavy equipment.",
        "about_33": "Implementasi digitalisasi dan pengembangan aplikasi untuk mendukung kegiatan operasional.",
        "about_34": "The Journey 2022–2023",
        "about_35": "Akuisisi TBBM Ketapang, VHS EP, VHS KAI, Fleet Management di Sorong & Ternate, Project APMS RPM, APMS Jatim Balinus.",
        "about_36": "The Journey 2024–2025",
        "about_37": "Fleet Management di wilayah RJBT, Batam, Baturaja, Lahat & Lubuk Linggau.",
        "about_38": "Fleet Safety LPG Jatibalinus & RJBT.",
        "about_39": "Angkutan FAME.",
        "about_40": "Angkutan Produk Breezon MC-32.",
        "about_41": "Awal berdiri sejak",
        "about_42": "30 Agustus 1996",
        "about_43": "sebagai PT. Elnusa Kawasan Komersial, PT Patra Logistik bervisi",
        "about_44": "menjadi pemimpin pasar logistik dan rantai suplai energi nasional.",
        "about_45": "VHS BBM Timah, Pembangunan dan Pengoperasian DPPU Labuan Bajo",
        "about_46": "Franco BBM TNI, Pengelolaan KSO DPPU H.A.S. Hanandjoeddin",
        "about_47": "Transportasi:",
        "about_48": "Transportasi Pelumas dari DSP Plumpang ke seluruh wilayah Indonesia Bagian Barat",
        "about_49": "Transportasi CNG",
        "about_50": "Warehouse Management System",
        "about_51": "Customs Clearance",
        "about_52": "Ekspansi pasar",
        "about_53": "ke BUMN Non Pertamina Group dan Ekspansi bisnis special haulage heavy equipment.",
        "about_54": "Implementasi digitalisasi",
        "about_55": "dan pengembangan aplikasi untuk mendukung kegiatan operasional.",
        "about_56": "TBBM Ketapang",
        "about_57": ", VHS EP, VHS KAI, Fleet Management di Sorong & Ternate, Project APMS RPM, APMS Jatim Balinus.",
        "about_58": "Fleet Management",
        "about_59": "di wilayah RJBT, Batam, Baturaja, Lahat & Lubuk Linggau.",
        "about_60": "Fleet Safety LPG",
        "about_61": "Jatibalinus & RJBT.",
        "about_62": "Angkutan FAME",
        "about_63": "Angkutan Produk Breezon MC-32",
        "about_64": "Dewan Komisaris",
        "about_65": "Budi YP Hutagaol",
        "about_66": "Komisaris Utama",
        "about_67": "Achmad Tjachja Nugraha",
        "about_68": "Komisaris Independent",
        "about_69": "Dewan Direksi",
        "about_70": "Yock Yorlando",
        "about_71": "Direktur Utama",
        "about_72": "Joko Priyambodo",
        "about_73": "Direktur Operasional & Pemasaran",
        "about_74": "Struktur Perusahaan",
        "about_75": "Bagan kepemilikan saham, posisi holding, serta daftar anak perusahaan, patungan, dan afiliasi PT Patra Logistik (anak perusahaan PT Pertamina Patra Niaga).",
        "about_76": "Government of",
        "about_77": "The Republic of Indonesia",
        "about_78": "PT Pertamina (Persero)",
        "about_79": "PT Pertamina Trans Kontinental",
        "about_80": "PATRA NIAGA",
        "about_81": "Pertamina Retail",
        "about_82": "Fuel & Non Fuel Retail Business",
        "about_83": "INTERNATIONAL",
        "about_84": "Pertamina International Marketing",
        "about_85": "International Trading",
        "about_86": "PETROCHEMICAL",
        "about_87": "Petrochemical Trading",
        "about_88": "EPC, O&M, Plant Services",
        "about_89": "Trading & Services",
        "about_90": "Marketing & Trading Aromatic & Olefin",
        "about_91": "Marketing & Trading LBO",
        "about_92": "Pertamina Lubricants",
        "about_93": "Lubricants & Special Chemical (Automotive Related)",
        "about_94": "PATRA LOGISTIK",
        "about_95": "Patra Logistik",
        "about_96": "Transport & Inventory Management",
        "about_97": "MAINTENANCE",
        "about_98": "Maintenance & Construction",
        "about_99": "Maintenance & Construction",
        "about_100": "Pertamina International Timor",
        "about_101": "B2B & B2C Downstream Business",
        "about_102": "Pedeve Indonesia",
        "about_103": "Investment and Business Portfolio Management",
        "about_104": "Anak Perusahaan (Subsidiary)",
        "about_105": "Perusahaan Patungan (Joint Venture)",
        "about_106": "Perusahaan Afiliasi (Affiliate)",
        "about_107": "Certification",
        "about_108": "Sebagai wujud komitmen terhadap kepuasan pelanggan, kesehatan, keselamatan, keamanan, dan lingkungan, kami menerapkan Manajemen Mutu serta Standar Health, Safety, Security and Environmental (HSSE). Komitmen kami dibuktikan dengan perolehan sertifikat standar internasional yang diperbarui secara berkala.",
        "about_109": "ISO 9001:2015",
        "about_110": "Sistem Manajemen Mutu",
        "about_111": "31 Desember 2021 – 30 Desember 2024",
        "about_112": "ISO 14001:2015",
        "about_113": "Sistem Manajemen Lingkungan",
        "about_114": "31 Desember 2021 – 30 Desember 2024",
        "about_115": "ISO 45001:2018",
        "about_116": "Sistem Manajemen Kesehatan dan Keselamatan Kerja",
        "about_117": "31 Desember 2021 – 30 Desember 2024",
        "about_118": "Sistem Manajemen Keselamatan dan Kesehatan Kerja",
        "about_119": "Kementerian Ketenagakerjaan RI",
        "about_120": "13 Mei 2022 – 12 Mei 2023",
        "about_121": "Penghargaan Korporasi",
        "about_122": "Apresiasi dan penghargaan atas pencapaian kinerja, keselamatan kerja, serta kontribusi sosial PT Patra Logistik.",
        "about_123": "Sales Leaders Awards of The Year 2025 MarkPlus",
        "about_124": "- Sales Strategy That Change The Game",
        "about_125": "- Strategic Key Account Growth",
        "about_126": "CSR Awards 2025 and CSR Brand Equity Summit 2025",
        "about_127": "CSR Equity Awards in Logistic Category",
        "about_128": "Sumatera Supplier Relationship Management (SRM) Summit 2025",
        "about_129": "Best Performance Sinergi Pertamina Group",
        "about_130": "SWA Media Awards 2024",
        "about_131": "Indonesia Best Business Transformation 2024",
        "about_132": "Indonesia Logistic Awards (ILA) 2024 by Supply Chain Indonesia",
        "about_133": "The Best Performer for Energy Logistic Distribution of The Year",
        "about_134": "Marketeers Editor's Choice Award (MECA) 2024",
        "about_135": "Business Transformation of The Year",
        "about_136": "The Iconomics Indonesia Innovation Awards 2024",
        "about_137": "Indonesia Innovation Company in Logistic Category",
        "about_138": "Indonesia Public Relations Summit 2024 By The Iconomics",
        "about_139": "Indonesia Popular Corporate Reputation Awards",
        "about_140": "Indonesia Fair Trusted Company GCG Awards 2023",
        "about_141": "Fair Trusted Company Based On Corporate Governance Perception Index (CGPI)",
        "about_142": "Vendor Days Awards Pertamina Patra Niaga Reg. Kalimantan, Sulawesi, Papua Maluku 2024",
        "about_143": "- Best Performance Pertamina Group Affiliates",
        "about_144": "- Business Support Penyaluran BBM 1 Harga",
        "about_145": "Vendor Day Awards PT Pertamina Lubricants 2024",
        "about_146": "The Best Synergistic Alliance Achievement",
        "about_147": "Best Practice Awards Pertamina Patra Niaga 2024",
        "about_148": "Performance Pencapaian ABI Fisik dan Finansial Anak Perusahaan Terbaik",
        "about_149": "Appreciation from President Director of PT Indonesia Air Asia",
        "about_150": "Pertamina Komodo Airport Aircraft Refueling Depot, Labuan Bajo",
        "about_151": "Nation Aviation Forum tahun 2023",
        "about_152": "DPPU KSO Terbaik oleh DPPU Banyuwangi Atas Penyelesaian Closing Audit 100%",
        "about_153": "Kantor Pusat",
        "about_154": "Garden Avenue Rasuna Lantai 1-3, Jalan Epicentrum Tengah No. 3, RT.2/RW.5, Karet Kuningan, Kecamatan Setiabudi, Jakarta Selatan.",
        "about_155": "(021)-25196699",
        "about_156": "info.patralogistik@pertamina.com",
        "about_157": "Whistle Blowing System",
        "about_158": "https://pertaminaclean.tipoffs.info/",
        "about_159": "AFFILIATE OF:",
        "about_160": "PERTAMINA PATRA NIAGA",
        "about_161": "Semua konten, logo, dan hak cipta dilindungi oleh PT Patra Logistik dan                         PT Pertamina (Persero).",

        "kembali_berita": "Kembali ke Daftar Berita",
        // Navbar
        "nav.about": "Tentang Kami",
        "nav.business": "Bisnis",
        "nav.investor": "Hubungan Investor",
        "nav.sustainability": "Sustainability",
        "nav.news": "Berita & Media",
        "nav.career": "Karir",
        "nav.contact": "HUBUNGI KAMI",
        "nav.about.profile": "Profil Perusahaan",
        "nav.about.vision": "Visi Misi",
        "nav.about.values": "Tata Nilai",
        "nav.about.history": "Sejarah",
        "nav.about.board": "Dewan Komisaris",
        "nav.about.directors": "Direksi",
        "nav.about.structure": "Struktur Organisasi",
        "nav.about.certification": "Sertifikasi",
        "nav.about.awards": "Penghargaan",
        "nav.biz.transport": "Transportasi",
        "nav.biz.inventory": "Inventory Management",
        "nav.biz.other": "Lainnya",
        "nav.biz.fleet": "Fleet Management",

        // Hero
        "hero.tag": "Penyaluran dan Transportasi",
        "hero.title": "Logistik Energi, Andal, <br>Aman, Terintegrasi",
        "hero.desc": "Memastikan pasokan energi nasional — aman, tepat waktu, tepat jumlah — dari Aceh hingga Papua.",
        "hero.btn.route": "Lihat Rute Penyaluran",
        "hero.btn.contact": "Hubungi Kami",
        "hero.track.subtitle": "REAL-TIME MONITORING",
        "hero.track.title": "Lacak Pengiriman",
        "hero.track.desc": "Masukkan nomor Delivery Order (DO) untuk memantau status pengiriman BBM & LPG Anda secara langsung.",
        "hero.track.placeholder": "Masukkan No. DO (Contoh: DO-PATRA-001)",
        "hero.track.btn": "LACAK SEKARANG",

        // Ticker
        "ticker.quality": "Tepat Mutu",
        "ticker.time": "Tepat Waktu",
        "ticker.quantity": "Tepat Jumlah",
        "ticker.place": "Tepat Tempat",
        "ticker.hsse": "HSSE Terintegrasi",
        "ticker.tracking": "Real-Time Tracking",
        "ticker.national": "Distribusi Nasional",
        "ticker.modern": "Armada Modern",

        // About Section
        "about.tag": "EST. SEJAK 1997",
        "about.title": "Tentang<br>Patra Logistik",
        "about.desc": "Temukan bagaimana kami menghadirkan efisiensi operasional yang tak tertandingi dalam distribusi energi. Dengan jaringan yang luas dan teknologi terkini, kami memastikan setiap pengiriman energi sampai tepat sasaran.",
        "about.stat.city": "Kota Operasi",
        "about.stat.accuracy": "Tracking Accuracy",
        "about.stat.ontime": "On-Time Delivery",
        "about.btn": "PELAJARI LEBIH LANJUT",

        // Services
        "services.tag": "Layanan Kami",
        "services.title": "Layanan & Solusi Logistik",
        "services.desc": "Kami hadir dengan layanan terintegrasi untuk memastikan setiap tetes energi sampai ke tujuan dengan aman dan tepat.",
        "services.tab.transport": "Transportasi",
        "services.tab.inventory": "Inventory Management",
        "services.tab.other": "Other Business",
        "services.card.more": "Selengkapnya",

        // Services Transport
        "srv.trans.1.title": "Pengangkutan BBM",
        "srv.trans.1.desc": "Pengiriman pelumas industri & otomotif Pertamina secara aman dengan jaminan keaslian dan anti-kontaminasi.",
        "srv.trans.2.title": "Pengangkutan Gas",
        "srv.trans.2.desc": "Pengiriman pelumas industri & otomotif Pertamina secara aman dengan jaminan keaslian dan anti-kontaminasi.",
        "srv.trans.3.title": "Pengangkutan Pelumas",
        "srv.trans.3.desc": "Pengiriman pelumas industri & otomotif Pertamina secara aman dengan jaminan keaslian dan anti-kontaminasi.",
        "srv.trans.4.title": "Transportasi Multimoda",
        "srv.trans.4.desc": "Solusi pengiriman terintegrasi antar moda darat, laut, dan udara secara efisien.",
        "srv.trans.5.title": "Pengangkutan Limbah B3",
        "srv.trans.5.desc": "Layanan pengelolaan dan pengangkutan limbah berbahaya tersertifikasi dan aman.",

        // Map Section
        "map.tag": "LAYANAN KAMI",
        "map.title": "Wilayah Operasi",
        "map.desc": "Menghubungkan rantai pasok energi Indonesia dari Sabang sampai Merauke secara presisi dan berkesinambungan melalui unit region strategis.",
        "map.instruction": "INTERAKTIF: KLIK WILAYAH REGION UNTUK DETAIL JANGKAUAN",
        "map.stat.1": "Retail Fuel Transport",
        "map.stat.2": "Industrial Fuel Transport",
        "map.stat.3": "Vendor Managed Inventory",
        "map.stat.4": "Total Project & Layanan",
        "map.stat.unit.project": "PROJECT",
        "map.stat.unit.location": "LOKASI",
        "map.stat.unit.total": "TOTAL",
        "map.panel.btn": "Informasi Project & Layanan",

        // RTC Section
        "rtc.pill": "PUSAT KENDALI OPERASI DIGITAL",
        "rtc.title": "Digital Logistic <span class='text-light-blue'>Solution</span>",
        "rtc.desc": "Sistem pengawasan digital terpadu yang memantau pergerakan armada, kondisi pengemudi, serta keselamatan muatan energi secara real-time demi mewujudkan <span class='text-bold-blue'>Zero Accident & High Reliability</span>.",
        "rtc.card.more": "SELENGKAPNYA",
        "rtc.card1.pill": "IOT TRACKER",
        "rtc.card1.title": "Fleet Management<br>System",
        "rtc.card1.desc": "Solusi GPS Tracker untuk Keamanan Armada Secara Real-Time",
        "rtc.card2.pill": "AI CAMERA",
        "rtc.card2.title": "Fatigue<br>Sensor",
        "rtc.card2.desc": "Mendeteksi kelelahan pengemudi dengan AI",
        "rtc.card3.pill": "SAFETY",
        "rtc.card3.title": "Over-Speed<br>Buzzer",
        "rtc.card3.desc": "Peringatan otomatis saat melebihi batas kecepatan",
        "rtc.card4.pill": "DASHCAM",
        "rtc.card4.title": "In-Cabin<br>Camera",
        "rtc.card4.desc": "Pemantauan visual kabin armada 24/7",

        // Footer
        "footer.desc": "Berkomitmen pada distribusi energi yang aman, andal, dan terintegrasi ke seluruh pelosok negeri.",
        "footer.col1": "PERUSAHAAN",
        "footer.col2": "INFORMASI PUBLIK",
        "footer.col3": "KANTOR PUSAT",
        "footer.copyright": "© 2026 PT Pertamina Patra Logistik. Hak Cipta Dilindungi Undang-Undang."
    },
    en: {
        "biz_0": "Logistics & Energy Solutions",
        "biz_1": "Our Business",
        "biz_2": "Providing an integrated, reliable, and international-standard energy logistics supply chain across Indonesia.",
        "biz_3": "Patra Logistik is here as a reliable energy logistics transportation partner, with an extensive service network, strict implementation of safety aspects, and technology support to ensure every distribution process runs safely, efficiently, and is monitored in real-time.",
        "biz_4": "Patra Logistik provides Fuel Oil (BBM) transportation services through the integrated, reliable, and safety-oriented management of Tank Truck Crews (AMT) and Fuel Tank Trucks. This service supports the distribution of fuel from the Fuel Terminal to gas stations, industries, and other distribution points.",
        "biz_5": "> Service Scheme",
        "biz_6": "Pertamina Fuel Depot",
        "biz_7": "Patra Logistik Supply Fleet",
        "biz_8": "Handover Location",
        "biz_9": "Patra Logistik provides Liquefied Petroleum Gas (LPG) transportation services using specialized pressurized tank truck fleets designed to maintain safety, quality, and reliability of gas distribution in liquid form.",
        "biz_10": "This service supports mass LPG supply distribution from depots or main terminals to LPG Bulk Filling Stations (SPBE) and other service points.",
        "biz_11": "> Service Scheme",
        "biz_12": "LPG Distribution Scheme (Mother-Daughter System)",
        "biz_13": "Mother Station",
        "biz_14": "Transport (Skid Tank)",
        "biz_15": "Daughter Station",
        "biz_16": "LNG Distribution Scheme (Virtual Pipeline System)",
        "biz_17": "LNG Plant/LNG Terminal",
        "biz_18": "LNG Filling Station",
        "biz_19": "Trucking + ISO Tank",
        "biz_20": "Regasification Facility",
        "biz_21": "LNG Customer",
        "biz_22": "Managing two-way lubricant supply chain distribution, reaching operational areas from Depot Supply Points (DSP) to distributors throughout Indonesia and vice versa.",
        "biz_23": "> Service Scheme",
        "biz_24": "Ujung Berung",
        "biz_25": "DISTRIBUTOR",
        "biz_26": "DISTRIBUTOR",
        "biz_27": "Door to Door",
        "biz_28": "Reliable and international-standard aviation fuel (Avtur) distribution services from Fuel Terminals (TBBM) to Aircraft Refueling Depots (DPPU) up to direct refueling to airlines.",
        "biz_29": "Large volume Avtur distribution using tank trucks (bridger avtur) from main TBBM/Refineries to airport DPPU storage tanks.",
        "biz_30": "Direct aircraft refueling services using refueller trucks or airport hydrant system dispensers.",
        "biz_31": "> Service Scheme",
        "biz_32": "Transportation of B3 waste (Hazardous and Toxic Materials) from energy logistics operations with official permits and very strict safety procedures to ensure comprehensive environmental protection.",
        "biz_33": "> Service Scheme",
        "biz_34": "B3 Waste Generator",
        "biz_35": "Licensed B3 Fleet",
        "biz_36": "B3 Processing Facility",
        "biz_37": "Why do companies entrust transportation to Patra Logistik?",
        "biz_38": "Nationwide Network",
        "biz_39": "Operational network spread across various regions of Indonesia, supporting broad and sustainable energy distribution needs.",
        "biz_40": "HSSE Principle",
        "biz_41": "Prioritizing Health, Safety, Security, and Environment principles in every operational activity to ensure services run safely and according to standards.",
        "biz_42": "Cost Effectiveness",
        "biz_43": "Operational optimization to support cost efficiency without compromising service quality, safety, and reliability.",
        "biz_44": "Real Time Monitoring",
        "biz_45": "Real-time fleet monitoring to ensure vehicle movements, routes, and distribution activities can be tracked accurately.",
        "biz_46": "Multi-Modal Integration",
        "biz_47": "Supporting the integration of various transportation modes to create more flexible, efficient, and connected logistics solutions.",
        "biz_48": "Inventory Management",
        "biz_49": "We are determined to provide the best service to you. With diverse fleets managed by dedicated and expert teams, we hope to deliver excellence to you.",
        "biz_50": "Fuel Terminal Ketapang, established in 2006, is a strategic energy storage and distribution center in West Kalimantan. Located in the Pawan River channel, this terminal is vital in supplying Fuel (Biosolar, Pertalite, Pertamax) to the Ketapang and Kayong Utara regions with a storage tank capacity reaching 7,200 kiloliters.",
        "biz_51": "FT Ketapang is equipped with a jetty for loading and unloading, as well as refueling with a capacity of 3,000 DWT.",
        "biz_52": "DWT Capacity",
        "biz_53": "Total Capacity",
        "biz_54": "Patra Logistik plays a strategic role in the warehouse management and distribution of PT Pertamina Lubricants (PTPL). This synergy is focused on strengthening the supply chain, optimizing warehouse infrastructure, and improving distribution services.",
        "biz_55": "The management and distribution of PT Pertamina Lubricants' Depot Supply Points include warehouse management such as Receiving, Storaging, Picking, as well as providing human resources for warehousing operations.",
        "biz_56": "DPPU (Aircraft Refueling Depot) is a form of collaboration between Pertamina Patra Niaga and PT Patra Logistik to manage aircraft refueling operations at various airports in Indonesia. This scheme aims to ensure the reliability of avtur stock and the efficiency of aircraft refueling services.",
        "biz_57": "Fuel management covering fuel delivery, fuel storage, up to fuel distribution and maintenance of fuel storage facilities available at the consumer's location (Vendor Held Stocks).",
        "biz_58": "> VHS Operations Flow Scheme",
        "biz_59": "Supply Source",
        "biz_60": "Patra Niaga Fuel Depot",
        "biz_61": "🚢 Ship (Sea)",
        "biz_62": "🚚 Fleet (Land)",
        "biz_63": "Consumer Location",
        "biz_64": "VHS Storage",
        "biz_65": "Storage Facility",
        "biz_66": "VHS Storage",
        "biz_67": "🚢 Supply Ship",
        "biz_68": "⚙️ Flowmeter",
        "biz_69": "🚛 Service Tank Truck",
        "biz_70": "Final Destination",
        "biz_71": "Customer Equipment",
        "biz_72": "(Ships, generators, heavy equipment, etc.)",
        "biz_73": "Professional management services for project material warehouses, spare parts, and supporting equipment for the energy industry. We implement modern WMS (Warehouse Management System) to ensure accurate inventory recording, real-time tracking, and optimal storage layout.",
        "biz_74": "Material Storage",
        "biz_75": "Storage of project materials and industrial equipment with safe and hygienic spatial layouts.",
        "biz_76": "Spare Part Management",
        "biz_77": "Periodic recording of vital spare part stock levels to minimize operational downtime.",
        "biz_78": "Other Business",
        "biz_79": "We are determined to provide the best service to you. With diverse fleets managed by dedicated and expert teams, we hope to deliver excellence to you.",
        "biz_80": "Light Passenger Vehicle rental services to support office and field operational activities of working partners in various operational areas throughout Indonesia. Our fleet is maintained periodically and supported by a safe driving monitoring system.",
        "biz_81": "Customs administration, export-import, and port licensing (Customs Clearance) services handled quickly, accurately, and in compliance with applicable legal regulations. We simplify the customs process for your energy commodities to ensure smooth distribution flow.",
        "biz_82": "Integrated information technology solutions to support logistics operations, including transportation management systems (TMS), real-time tracking, supply chain data integration, and IT infrastructure maintenance in remote operating areas.",
        "biz_83": "Provision of professional and certified manpower (such as tank truck drivers/AMT, logistics staff, field operations) to ensure strict safety standards (HSSE) and high work efficiency in your energy distribution ecosystem.",
        "biz_84": "Transportation services for non-fuel energy products, such as Fatty Acid Methyl Ester (FAME) and eco-friendly refrigerants Breezon MC (hydrocarbon refrigerants from Pertamina) for industrial, automotive, and eco-friendly air conditioning needs.",
        "biz_85": "FAME Transportation",
        "biz_86": "Transportation of FAME (Fatty Acid Methyl Ester) as the main biodiesel blend component to support the national renewable energy mix and the government's eco-friendly programs.",
        "biz_87": "Bioenergy Distribution",
        "biz_88": "Breezon MC Transportation",
        "biz_89": "Distribution and transportation of Pertamina's Breezon MC hydrocarbon refrigerant as a safe and highly energy-efficient eco-friendly air cooling medium solution.",
        "biz_90": "Green Refrigerant Transport",
        "biz_91": "Fleet Management",
        "biz_92": "Through integrated",
        "biz_93": "Fleet Management",
        "biz_94": "services, Patra Logistik presents comprehensive solutions to ensure every fleet operates at peak performance, starting from daily operational management, vehicle performance monitoring, periodic care and maintenance, to optimizing fleet utilization.",
        "biz_95": "Services and solutions we manage",
        "biz_96": "Fleet Operations",
        "biz_97": "Track all vehicle operational transactions, monitor fuel usage, to accurate travel history recording to maximize the use of each vehicle.",
        "biz_98": "Route Optimization",
        "biz_99": "Know the shortest and fastest route to your destination considering factors such as traffic conditions, distance, weather forecasts, and travel time. Increase travel time efficiency.",
        "biz_100": "Maintenance Management",
        "biz_101": "Real-time notifications when your fleet needs repair. Automatically set maintenance schedules based on time intervals. Minimize your vehicle downtime.",
        "biz_102": "Driver Management",
        "biz_103": "Manage all driver data in a centralized driver management system. Monitor location, working hours, and driver activities in real-time.",
        "biz_104": "Seamless IoT Integration",
        "biz_105": "Easy integration of geofencing, GPS, odometers, sensors, and much more to monitor location, speed, and vehicle operational conditions in real-time.",
        "biz_106": "Performance Report",
        "biz_107": "Provide detailed data regarding vehicle usage, including fuel consumption to speed, which can be used to make better business decisions.",
        "biz_108": "Operational System & Depot Reach",
        "biz_109": "Maintenance Management System (MMS)",
        "biz_110": "Security & Surveillance",
        "biz_111": "GPS TRACK MT & DASHCAM",
        "biz_112": "Operation & Maintenance",
        "biz_113": "Tyre Management System (TMS)",
        "biz_114": "Traffic Road Control (TRC)",
        "biz_115": "Human Resource (Own Use)",
        "biz_116": "Fleet Project",
        "biz_117": "Head Office",
        "biz_118": "Garden Avenue Rasuna Floors 1-3, Jalan Epicentrum Tengah No. 3, RT.2/RW.5, Karet Kuningan, Setiabudi District, South Jakarta.",
        "biz_119": "(021)-25196699",
        "biz_120": "info.patralogistik@pertamina.com",
        "biz_121": "Whistle Blowing System",
        "biz_122": "https://pertaminaclean.tipoffs.info/",
        "biz_123": "AFFILIATE OF:",
        "biz_124": "PERTAMINA PATRA NIAGA",
        "biz_125": "All contents, logos, and copyrights are protected by PT Patra Logistik and                         PT Pertamina (Persero).",

        "about_0": "Corporate Profile",
        "about_1": "About Patra Logistik",
        "about_2": "Integrated energy logistics solutions with high safety and compliance standards for the nation.",
        "about_3": "Vision & Mission",
        "about_4": "\"To become a Leading, Reliable, and World-Class Integrated Energy Logistics Service Provider in Indonesia.\"",
        "about_5": "Organizing efficient, safe, and timely integrated energy logistics services to ensure national energy supply.",
        "about_6": "Implementing the highest level of HSSE (Health, Safety, Security & Environment) practices across the entire operational chain.",
        "about_7": "Building mutually beneficial business synergies with strategic partners and providing optimal added value to stakeholders.",
        "about_8": "Corporate Values (AKHLAK)",
        "about_9": "As a subsidiary of the state-owned Pertamina group, we uphold the core value of AKHLAK in carrying out our daily operational functions:",
        "about_10": "Upholding the trust given with high integrity and taking full responsibility.",
        "about_11": "Continuously learning, innovating, and improving capabilities to deliver the best work results.",
        "about_12": "Caring for, empathizing with, and respecting the diversity and contributions of each individual.",
        "about_13": "Highly dedicated and prioritizing the nation's interests as well as the company's progress.",
        "about_14": "Quick to adapt, agile in facing business challenges, and continuously making improvements.",
        "about_15": "COLLABORATIVE",
        "about_16": "Building synergistic cooperation for common goals and national energy fulfillment.",
        "about_17": "COMPANY HISTORY",
        "about_18": "PT Patra Logistik originated from PT. Elnusa Kawasan Komersial, established on August 30, 1996, to manage the Commercial Area at Graha Elnusa TB Simatupang Kav 1-B, South Jakarta. On August 16, 2005, PT. Elnusa Kawasan Komersial changed its name to PT. Patra Logistik and became a subsidiary of PT. Pertamina Patra Niaga. PT Patra Logistik is now located at Garden Avenue Rasuna (floors 1-3) Jl. Epicentrum Tengah No. 3, Setiabudi, South Jakarta.",
        "about_19": "PT Patra Logistik operates in the downstream oil and gas business, focusing on logistics service provision and other logistics support services. Committed and fully striving with the resources we have to strengthen its competence as a Logistics Company by providing prime services, PT Patra Logistik puts forward a professional and transparent work ethic with high integrity oriented towards customer and stakeholder satisfaction, welfare, and responsiveness in facing dynamics",
        "about_20": "The Journey 2012–2013",
        "about_21": "Tin Fuel VHS, Construction and Operation of Labuan Bajo DPPU",
        "about_22": "The Journey 2016–2017",
        "about_23": "TNI Fuel Franco, KSO Management of H.A.S. Hanandjoeddin DPPU",
        "about_24": "The Journey 2018–2019",
        "about_25": "Transportation:",
        "about_26": "Lubricant Transportation from DSP Plumpang to all regions of Western Indonesia",
        "about_27": "CNG Transportation",
        "about_28": "Warehouse Management System",
        "about_29": "Customs Clearance",
        "about_30": "The Journey 2019–2020",
        "about_31": "The Journey 2020–2021",
        "about_32": "Market expansion to Non-Pertamina Group SOEs and business expansion in special haulage heavy equipment.",
        "about_33": "Implementation of digitalization and application development to support operational activities.",
        "about_34": "The Journey 2022–2023",
        "about_35": "Acquisition of Ketapang TBBM, EP VHS, KAI VHS, Fleet Management in Sorong & Ternate, RPM APMS Project, Jatim Balinus APMS.",
        "about_36": "The Journey 2024–2025",
        "about_37": "Fleet Management in RJBT, Batam, Baturaja, Lahat & Lubuk Linggau areas.",
        "about_38": "LPG Fleet Safety in Jatibalinus & RJBT.",
        "about_39": "FAME Transportation.",
        "about_40": "Breezon MC-32 Product Transportation.",
        "about_41": "Initially established since",
        "about_42": "August 30, 1996",
        "about_43": "as PT. Elnusa Kawasan Komersial, PT Patra Logistik envisions",
        "about_44": "to become the market leader in national energy logistics and supply chain.",
        "about_45": "Tin Fuel VHS, Construction and Operation of Labuan Bajo DPPU",
        "about_46": "TNI Fuel Franco, KSO Management of H.A.S. Hanandjoeddin DPPU",
        "about_47": "Transportation:",
        "about_48": "Lubricant Transportation from DSP Plumpang to all regions of Western Indonesia",
        "about_49": "CNG Transportation",
        "about_50": "Warehouse Management System",
        "about_51": "Customs Clearance",
        "about_52": "Market expansion",
        "about_53": "to Non-Pertamina Group SOEs and business expansion in special haulage heavy equipment.",
        "about_54": "Implementation of digitalization",
        "about_55": "and application development to support operational activities.",
        "about_56": "Ketapang TBBM",
        "about_57": ", EP VHS, KAI VHS, Fleet Management in Sorong & Ternate, RPM APMS Project, Jatim Balinus APMS.",
        "about_58": "Fleet Management",
        "about_59": "in RJBT, Batam, Baturaja, Lahat & Lubuk Linggau areas.",
        "about_60": "LPG Fleet Safety",
        "about_61": "Jatibalinus & RJBT.",
        "about_62": "FAME Transportation",
        "about_63": "Breezon MC-32 Product Transportation",
        "about_64": "Board of Commissioners",
        "about_65": "Budi YP Hutagaol",
        "about_66": "President Commissioner",
        "about_67": "Achmad Tjachja Nugraha",
        "about_68": "Independent Commissioner",
        "about_69": "Board of Directors",
        "about_70": "Yock Yorlando",
        "about_71": "President Director",
        "about_72": "Joko Priyambodo",
        "about_73": "Director of Operations & Marketing",
        "about_74": "Corporate Structure",
        "about_75": "Shareholding structure, holding position, and list of subsidiaries, joint ventures, and affiliates of PT Patra Logistik (a subsidiary of PT Pertamina Patra Niaga).",
        "about_76": "Government of",
        "about_77": "The Republic of Indonesia",
        "about_78": "PT Pertamina (Persero)",
        "about_79": "PT Pertamina Trans Kontinental",
        "about_80": "PATRA NIAGA",
        "about_81": "Pertamina Retail",
        "about_82": "Fuel & Non Fuel Retail Business",
        "about_83": "INTERNATIONAL",
        "about_84": "Pertamina International Marketing",
        "about_85": "International Trading",
        "about_86": "PETROCHEMICAL",
        "about_87": "Petrochemical Trading",
        "about_88": "EPC, O&M, Plant Services",
        "about_89": "Trading & Services",
        "about_90": "Marketing & Trading Aromatic & Olefin",
        "about_91": "Marketing & Trading LBO",
        "about_92": "Pertamina Lubricants",
        "about_93": "Lubricants & Special Chemical (Automotive Related)",
        "about_94": "PATRA LOGISTIK",
        "about_95": "Patra Logistik",
        "about_96": "Transport & Inventory Management",
        "about_97": "MAINTENANCE",
        "about_98": "Maintenance & Construction",
        "about_99": "Maintenance & Construction",
        "about_100": "Pertamina International Timor",
        "about_101": "B2B & B2C Downstream Business",
        "about_102": "Pedeve Indonesia",
        "about_103": "Investment and Business Portfolio Management",
        "about_104": "Subsidiary",
        "about_105": "Joint Venture",
        "about_106": "Affiliate",
        "about_107": "Certification",
        "about_108": "As a manifestation of our commitment to customer satisfaction, health, safety, security, and the environment, we implement Quality Management and Health, Safety, Security, and Environmental (HSSE) Standards. Our commitment is proven by obtaining internationally updated standard certificates.",
        "about_109": "ISO 9001:2015",
        "about_110": "Quality Management System",
        "about_111": "December 31, 2021 – December 30, 2024",
        "about_112": "ISO 14001:2015",
        "about_113": "Environmental Management System",
        "about_114": "December 31, 2021 – December 30, 2024",
        "about_115": "ISO 45001:2018",
        "about_116": "Occupational Health and Safety Management System",
        "about_117": "December 31, 2021 – December 30, 2024",
        "about_118": "Occupational Safety and Health Management System",
        "about_119": "Ministry of Manpower of the Republic of Indonesia",
        "about_120": "May 13, 2022 – May 12, 2023",
        "about_121": "Corporate Awards",
        "about_122": "Appreciation and awards for performance achievements, occupational safety, and social contributions of PT Patra Logistik.",
        "about_123": "Sales Leaders Awards of The Year 2025 MarkPlus",
        "about_124": "- Sales Strategy That Change The Game",
        "about_125": "- Strategic Key Account Growth",
        "about_126": "CSR Awards 2025 and CSR Brand Equity Summit 2025",
        "about_127": "CSR Equity Awards in Logistic Category",
        "about_128": "Sumatera Supplier Relationship Management (SRM) Summit 2025",
        "about_129": "Best Performance Synergy Pertamina Group",
        "about_130": "SWA Media Awards 2024",
        "about_131": "Indonesia Best Business Transformation 2024",
        "about_132": "Indonesia Logistic Awards (ILA) 2024 by Supply Chain Indonesia",
        "about_133": "The Best Performer for Energy Logistic Distribution of The Year",
        "about_134": "Marketeers Editor's Choice Award (MECA) 2024",
        "about_135": "Business Transformation of The Year",
        "about_136": "The Iconomics Indonesia Innovation Awards 2024",
        "about_137": "Indonesia Innovation Company in Logistic Category",
        "about_138": "Indonesia Public Relations Summit 2024 By The Iconomics",
        "about_139": "Indonesia Popular Corporate Reputation Awards",
        "about_140": "Indonesia Fair Trusted Company GCG Awards 2023",
        "about_141": "Fair Trusted Company Based On Corporate Governance Perception Index (CGPI)",
        "about_142": "Vendor Days Awards Pertamina Patra Niaga Reg. Kalimantan, Sulawesi, Papua Maluku 2024",
        "about_143": "- Best Performance Pertamina Group Affiliates",
        "about_144": "- Business Support for 1-Price Fuel Distribution",
        "about_145": "Vendor Day Awards PT Pertamina Lubricants 2024",
        "about_146": "The Best Synergistic Alliance Achievement",
        "about_147": "Best Practice Awards Pertamina Patra Niaga 2024",
        "about_148": "Best Subsidiary Physical and Financial ABI Achievement Performance",
        "about_149": "Appreciation from President Director of PT Indonesia Air Asia",
        "about_150": "Pertamina Komodo Airport Aircraft Refueling Depot, Labuan Bajo",
        "about_151": "National Aviation Forum 2023",
        "about_152": "Best KSO DPPU by Banyuwangi DPPU for 100% Audit Closing Completion",
        "about_153": "Head Office",
        "about_154": "Garden Avenue Rasuna Floors 1-3, Jalan Epicentrum Tengah No. 3, RT.2/RW.5, Karet Kuningan, Setiabudi District, South Jakarta.",
        "about_155": "(021)-25196699",
        "about_156": "info.patralogistik@pertamina.com",
        "about_157": "Whistle Blowing System",
        "about_158": "https://pertaminaclean.tipoffs.info/",
        "about_159": "AFFILIATE OF:",
        "about_160": "PERTAMINA PATRA NIAGA",
        "about_161": "All contents, logos, and copyrights are protected by PT Patra Logistik and                         PT Pertamina (Persero).",

        "kembali_berita": "Back to News List",
        // Navbar
        "nav.about": "About Us",
        "nav.business": "Business",
        "nav.investor": "Investor Relations",
        "nav.sustainability": "Sustainability",
        "nav.news": "News & Media",
        "nav.career": "Careers",
        "nav.contact": "CONTACT US",
        "nav.about.profile": "Company Profile",
        "nav.about.vision": "Vision & Mission",
        "nav.about.values": "Core Values",
        "nav.about.history": "History",
        "nav.about.board": "Board of Commissioners",
        "nav.about.directors": "Board of Directors",
        "nav.about.structure": "Organizational Structure",
        "nav.about.certification": "Certifications",
        "nav.about.awards": "Awards",
        "nav.biz.transport": "Transportation",
        "nav.biz.inventory": "Inventory Management",
        "nav.biz.other": "Other Services",
        "nav.biz.fleet": "Fleet Management",

        // Hero
        "hero.tag": "Distribution and Transportation",
        "hero.title": "Energy Logistics, Reliable, <br>Safe, Integrated",
        "hero.desc": "Ensuring the national energy supply — safely, on time, in the right quantity — from Aceh to Papua.",
        "hero.btn.route": "View Distribution Routes",
        "hero.btn.contact": "Contact Us",
        "hero.track.subtitle": "REAL-TIME MONITORING",
        "hero.track.title": "Track Shipment",
        "hero.track.desc": "Enter your Delivery Order (DO) number to monitor the delivery status of your Fuel & LPG directly.",
        "hero.track.placeholder": "Enter DO Number (e.g., DO-PATRA-001)",
        "hero.track.btn": "TRACK NOW",

        // Ticker
        "ticker.quality": "Right Quality",
        "ticker.time": "On Time",
        "ticker.quantity": "Right Quantity",
        "ticker.place": "Right Place",
        "ticker.hsse": "Integrated HSSE",
        "ticker.tracking": "Real-Time Tracking",
        "ticker.national": "National Distribution",
        "ticker.modern": "Modern Fleet",

        // About Section
        "about.tag": "EST. SINCE 1997",
        "about.title": "About<br>Patra Logistik",
        "about.desc": "Discover how we deliver unparalleled operational efficiency in energy distribution. With a vast network and latest technology, we ensure every energy shipment arrives perfectly on target.",
        "about.stat.city": "Operating Cities",
        "about.stat.accuracy": "Tracking Accuracy",
        "about.stat.ontime": "On-Time Delivery",
        "about.btn": "LEARN MORE",

        // Services
        "services.tag": "Our Services",
        "services.title": "Logistics Solutions & Services",
        "services.desc": "We provide integrated services to ensure every drop of energy reaches its destination safely and accurately.",
        "services.tab.transport": "Transportation",
        "services.tab.inventory": "Inventory Management",
        "services.tab.other": "Other Business",
        "services.card.more": "Read More",

        // Services Transport
        "srv.trans.1.title": "Fuel Transport",
        "srv.trans.1.desc": "Safe delivery of Pertamina industrial & automotive fuels with guaranteed authenticity and zero contamination.",
        "srv.trans.2.title": "Gas Transport",
        "srv.trans.2.desc": "Safe delivery of Pertamina industrial & automotive gas with guaranteed authenticity and zero contamination.",
        "srv.trans.3.title": "Lubricants Transport",
        "srv.trans.3.desc": "Safe delivery of Pertamina industrial & automotive lubricants with guaranteed authenticity and zero contamination.",
        "srv.trans.4.title": "Multimodal Transport",
        "srv.trans.4.desc": "Integrated shipping solutions across land, sea, and air efficiently.",
        "srv.trans.5.title": "B3 Waste Transport",
        "srv.trans.5.desc": "Certified and safe hazardous waste management and transportation services.",

        // Map Section
        "map.tag": "OUR COVERAGE",
        "map.title": "Operational Areas",
        "map.desc": "Connecting Indonesia's energy supply chain from Sabang to Merauke precisely and sustainably through strategic regional units.",
        "map.instruction": "INTERACTIVE: CLICK REGIONAL AREAS FOR COVERAGE DETAILS",
        "map.stat.1": "Retail Fuel Transport",
        "map.stat.2": "Industrial Fuel Transport",
        "map.stat.3": "Vendor Managed Inventory",
        "map.stat.4": "Total Projects & Services",
        "map.stat.unit.project": "PROJECTS",
        "map.stat.unit.location": "LOCATIONS",
        "map.stat.unit.total": "TOTAL",
        "map.panel.btn": "Project & Service Information",

        // RTC Section
        "rtc.pill": "DIGITAL OPERATIONS CONTROL CENTER",
        "rtc.title": "Digital Logistic <span class='text-light-blue'>Solution</span>",
        "rtc.desc": "Integrated digital surveillance system that monitors fleet movement, driver conditions, and energy cargo safety in real-time to realize <span class='text-bold-blue'>Zero Accident & High Reliability</span>.",
        "rtc.card.more": "READ MORE",
        "rtc.card1.pill": "IOT TRACKER",
        "rtc.card1.title": "Fleet Management<br>System",
        "rtc.card1.desc": "GPS Tracker solution for Real-Time Fleet Security",
        "rtc.card2.pill": "AI CAMERA",
        "rtc.card2.title": "Fatigue<br>Sensor",
        "rtc.card2.desc": "Detects driver fatigue utilizing AI",
        "rtc.card3.pill": "SAFETY",
        "rtc.card3.title": "Over-Speed<br>Buzzer",
        "rtc.card3.desc": "Automatic warning when exceeding speed limits",
        "rtc.card4.pill": "DASHCAM",
        "rtc.card4.title": "In-Cabin<br>Camera",
        "rtc.card4.desc": "24/7 visual monitoring of the fleet cabin",

        // Footer
        "footer.desc": "Committed to safe, reliable, and integrated energy distribution across the nation.",
        "footer.col1": "COMPANY",
        "footer.col2": "PUBLIC INFORMATION",
        "footer.col3": "HEAD OFFICE",
        "footer.copyright": "© 2026 PT Pertamina Patra Logistik. All Rights Reserved."
    }
};
